### PRODUCTION CONFIGURATION for production application ###  (warning: avoid tabs, indent with two spaces)

spring:
  datasource:
    username: ${MANON_PROD_SQL_USERNAME}
    password: ${MANON_PROD_SQL_PASSWORD}
    url: ${MANON_PROD_SQL_JDBC_URL}

manon:
  default-user:
    admin:
      username: ${MANON_PROD_ADMIN_USERNAME}
      password: ${MANON_PROD_ADMIN_PASSWORD}
    actuator:
      username: ${MANON_PROD_ACTUATOR_USERNAME}
      password: ${MANON_PROD_ACTUATOR_PASSWORD}
    dev:
      username: ${MANON_PROD_DEV_USERNAME}
      password: ${MANON_PROD_DEV_PASSWORD}
