### DOCKER CONTAINER CONFIGURATION ###  (warning: avoid tabs, indent with two spaces)

spring:
  datasource:
    username: root
    password: woot
    url: jdbc:mariadb://maria:3306/manon?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useMysqlMetadata=true
  jpa.hibernate.ddl-auto: update
