version: '3.4'

services:

  maria-test:
    container_name: maria-test
    image: mariadb:10.4.11 # see https://hub.docker.com/_/mariadb/
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: woot
      MYSQL_DATABASE: manon

  maria-batch-test:
    container_name: maria-batch-test
    image: mariadb:10.4.11 # see https://hub.docker.com/_/mariadb/
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: woot
      MYSQL_DATABASE: manon_batch

  postgres-test:
    container_name: postgres-test
    image: postgres:12.1 # see https://hub.docker.com/_/postgres/
    ports:
      - "5440:5432"
    environment:
      POSTGRES_PASSWORD: woot
      POSTGRES_DB: manon

  postgres-batch-test:
    container_name: postgres-batch-test
    image: postgres:12.1 # see https://hub.docker.com/_/postgres/
    ports:
      - "5441:5432"
    environment:
      POSTGRES_PASSWORD: woot
      POSTGRES_DB: manon_batch

  redis-test:
    container_name: redis-test
    image: redis:5.0.7-alpine # see https://hub.docker.com/_/redis/
    ports:
      - "6380:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
